house_pricing:
  train_dataset: /home/sasha/Desktop/programming/ai/kaggle_house_prices/train.csv
  test_dataset: /home/sasha/Desktop/programming/ai/kaggle_house_prices/test.csv
classification:
  wdbc: /home/sasha/Desktop/programming/ai/wdbc/data.csv
  mushrooms: /home/sasha/Desktop/programming/ai/mushrooms/mushrooms.csv
clustering:
  flowcytometry: /home/sasha/Desktop/programming/ai/flow_cytometry
